export const ROLES = {
  OWNER: "OWNER",
  INSPECTOR: "INSPECTOR",
  ADMIN: "ADMIN",
};


export const APPLICATION_STATUS = {
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  ASSIGNED: "ASSIGNED",
  INSPECTION_SCHEDULED:
    "INSPECTION_SCHEDULED",
  INSPECTION_IN_PROGRESS:
    "INSPECTION_IN_PROGRESS",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};


export const INSTRUMENT_STATUS = {
  ACTIVE: "ACTIVE",
  PENDING_VERIFICATION:
    "PENDING_VERIFICATION",
  VERIFIED: "VERIFIED",
  EXPIRED: "EXPIRED",
  SUSPENDED: "SUSPENDED",
};


export const INSPECTION_RESULT = {
  PASSED: "PASSED",
  FAILED: "FAILED",
  CONDITIONAL: "CONDITIONAL",
};


export const CERTIFICATE_STATUS = {
  VALID: "VALID",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
};


export const APPLICATION_TYPES = {
  NEW: "NEW",
  RENEWAL: "RENEWAL",
  REVERIFICATION:
    "REVERIFICATION",
};